# Generated by Django 2.0.6 on 2018-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=1000000)),
                ('expire', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=10)),
            ],
        ),
    ]
